- name: Create ansible config directories
  become: true
  file:
     path: /opt/ansible
     state: directory
     mode: 0770
- name: Synchronize pg_hba.conf
  become: true
  copy:
    dest: /opt/ansible/pg_hba.conf
    src: files/pg_hba.conf
    mode: 0770
- name: Download Postgres Build Tag 
  become: elquico
  delegate_to: localhost
  shell: ~/minio/mc cp local/build-tags/postgres files/build_tags/postgres
- name: Init Postgres Data Directory
  become: true
  file:
    path: ~/postgres
    state: directory
    owner: elquico
    group: docker
- name: Start Postgres Container
  docker_container:
    name: postgres
    image: "{{pg_build_tag}}"
    volumes: 
      - ~/postgres:/var/lib/postgresql/data,rwz
    ports: 
      - 5432:5432
    env:
      POSTGRES_PASSWORD: "{{PG_PASSWORD}}"
      POSTGRES_USER: "{{PG_USER}}"
      POSTGRES_DB: "castello"
- name: Copy pg_hba into docker Container
  become: true
  shell: docker cp /opt/ansible/pg_hba.conf postgres:/var/lib/postgresql/data/pg_hba.conf
  
